services:
  fundingbot:
    build: .
    image: fundingbot
    container_name: fundingbot
    user: "1000:1000"   
    restart: unless-stopped 
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
